apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediplus-deployment
  labels:
    app: mediplus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediplus
  template:
    metadata:
      labels:
        app: mediplus
    spec:
      containers:
        - name: mediplus-container
          image: 318689657850.dkr.ecr.us-east-1.amazonaws.com/kubernetes-registry:20
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediplus-service
spec:
  type: LoadBalancer
  selector:
    app: mediplus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
